### ISSUE TITLE
Upgrading to v1.0.4 causes significant color changes in Go

### ISSUE THREAD

**Issue by rileythomp** [berni23/berni-dark#3]
Thanks for this theme! Have been using it for a few weeks and like it a lot. 

I upgraded to v1.0.4 recently and there were significant color changes that I'm not sure were intended?

It now looks like this compared to the example in the readme.

| v1.0.4 | v1.0.3 |
|---|---|
| <img width="500" alt="updated-example" src="https://user-images.githubusercontent.com/35535783/230720336-a179def6-24df-44f4-a03c-a9fed6fe6ff7.png"> |  <img width="500" alt="readme-example" src="https://i.imgur.com/79Fpbxj.png"> |

Notice that variables and packages names that used to be white are now yellow.

If this was intended then feel free to ignore and I'll stick to v1.0.3, just wanted to mention it in case it wasn't intended.

**Comment by berni23** [comment]
You are absolutely right. A lot of changes were made in order to upgrade de
theme for typescript and Javascript. I realized now that some of the
changes were applied to the general scope, which was not intended at all. I
will release another version rolling back the previous changes.

Thanks for the email. If you have any suggestions regarding the theme,
feel free to let me know.


Bernat

**Comment by rileythomp** [comment]
Ah makes sense, thanks! New version looks good so will close this issue.
